import type { Metadata } from "next";
import "./globals.css";
import "./reasonos.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { SiteAnalytics } from "@/components/SiteAnalytics";
import { siteUrl } from "@/lib/site";
export const metadata: Metadata = { metadataBase:new URL(siteUrl), title:{default:"Arjan Singh Puniani | Neural Engineer Pursuing Medicine",template:"%s | Arjan Singh Puniani"},description:"Arjan Singh Puniani builds evidence-aware systems across neural engineering, rehabilitation, clinical reasoning, and motorsport safety.",alternates:{canonical:"/"},openGraph:{type:"website",url:siteUrl,title:"Arjan Singh Puniani | Neural Engineer Pursuing Medicine",description:"Evidence-aware systems across neural engineering, rehabilitation, clinical reasoning, and motorsport safety.",siteName:"Arjan Singh Puniani",images:[{url:"/images/hero/arj_kuzneski-hero.png",width:1200,height:1500,alt:"Arjan Singh Puniani holding the Kuzneski Innovation Cup"}]},twitter:{card:"summary_large_image",title:"Arjan Singh Puniani | Neural Engineer Pursuing Medicine",description:"Evidence-aware systems across neural engineering, rehabilitation, clinical reasoning, and motorsport safety.",images:["/images/hero/arj_kuzneski-hero.png"]},robots:{index:true,follow:true},manifest:"/manifest.webmanifest",verification:{google:process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,other:{"msvalidate.01":process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION??""}}};
export default function RootLayout({children}:{children:React.ReactNode}) { const schema=[{"@context":"https://schema.org","@type":"Person",name:"Arjan Singh Puniani",alternateName:"Arjan Puniani",url:siteUrl,image:`${siteUrl}/images/hero/arj_kuzneski-hero.png`,jobTitle:"Neural engineer",description:"Neural engineer and medical-school applicant working across rehabilitation, clinical reasoning, neurotechnology, and motorsport safety.",alumniOf:[{"@type":"CollegeOrUniversity",name:"University of Pittsburgh"},{"@type":"CollegeOrUniversity",name:"University of California, Berkeley"}],knowsAbout:["Neural engineering","Brain-computer interfaces","Clinical research","Medical education","Motorsport safety"]},{"@context":"https://schema.org","@type":"WebSite",name:"Arjan Singh Puniani",url:siteUrl,author:{"@type":"Person",name:"Arjan Singh Puniani",url:`${siteUrl}/about`}}]; return <html lang="en"><body><a href="#main" className="sr-only focus:not-sr-only">Skip to content</a><Header/><main id="main">{children}</main><Footer/><SiteAnalytics/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></body></html>; }
