import assert from 'node:assert/strict';
import {inspectCharacterAsset} from '../dist/animation/CharacterAssetIntake.js';
const arrays=[new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),new Float32Array([0,0,0,1,0,0,0,1,0]),new Float32Array([0,0,1,0,0,1,0,0,1]),new Uint8Array(12),new Float32Array([1,0,0,0,1,0,0,0,1,0,0,0])];
const doc={asset:{version:'2.0'},nodes:[{name:'hips'}],skins:[{joints:[0],inverseBindMatrices:0}],meshes:[{primitives:[{attributes:{POSITION:1,NORMAL:2,JOINTS_0:3,WEIGHTS_0:4},material:0}]}],materials:[{name:'shirt'}],bufferViews:arrays.map((a,i)=>({buffer:i,byteLength:a.byteLength})),accessors:arrays.map((a,i)=>({bufferView:i,componentType:i===3?5121:5126,count:i===0?1:3,type:i===0?'MAT4':i<3?'VEC3':'VEC4'}))};
const meta={author:'QA fixture',source:'synthetic triangle, not a character asset',license:'CC0',sha256:'a'.repeat(64),boneMap:{hips:'hips'}};
// Use an actual supported rig joint, leaving the artist-facing glTF name explicit.
const {BONE}=await import('../dist/animation/CharacterSkin.js');meta.boneMap.hips=Object.keys(BONE)[0];
const inspect=(d=doc,m=meta,b=arrays.map(a=>a.buffer))=>inspectCharacterAsset(d,b,m);
assert.equal(inspect().primitives[0].geometry.positions.length,9);
for(const mutate of [d=>d.asset.version='1.0',d=>d.skins[0].joints=[0,0],d=>d.accessors[1].count=1000,d=>d.bufferViews[1].byteLength=1,d=>d.meshes[0].primitives[0].targets=[{}],d=>d.animations=[{}],d=>d.materials[0].normalTexture={},d=>d.accessors[3].componentType=5126,d=>d.accessors[1].byteOffset=.5,d=>d.accessors[3].normalized=true,d=>d.accessors[4].componentType=5121]){const d=structuredClone(doc);mutate(d);assert.throws(()=>inspect(d));}
assert.throws(()=>inspect(doc,{...meta,license:''}));assert.throws(()=>inspect(doc,{...meta,boneMap:{}}));
const bad=arrays.map(a=>a.buffer.slice(0));new Float32Array(bad[4])[0]=.2;assert.throws(()=>inspect(doc,meta,bad),/normalized/);
const nan=arrays.map(a=>a.buffer.slice(0));new Float32Array(nan[1])[0]=NaN;assert.throws(()=>inspect(doc,meta,nan),/finite/);
assert.throws(()=>inspectCharacterAsset(new ArrayBuffer(20),[],meta),/header/);
console.log('Asset intake accepts a weighted synthetic triangle and rejects 16 malformed/unsupported cases; no professional asset supplied.');
// A real GLB container exercises JSON/BIN parsing, not only the object adapter.
const glbDoc=structuredClone(doc);let offset=0;glbDoc.bufferViews=arrays.map(a=>{const v={buffer:0,byteOffset:offset,byteLength:a.byteLength};offset+=a.byteLength;return v});glbDoc.buffers=[{byteLength:offset}];glbDoc.nodes.push({mesh:0,skin:0});glbDoc.scenes=[{nodes:[0,1]}];glbDoc.scene=0;glbDoc.accessors[1].min=[0,0,0];glbDoc.accessors[1].max=[1,1,0];
let json=Buffer.from(JSON.stringify(glbDoc));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const binary=Buffer.concat(arrays.map(a=>Buffer.from(a.buffer)));const glb=Buffer.alloc(12+8+json.length+8+binary.length);glb.writeUInt32LE(0x46546c67,0);glb.writeUInt32LE(2,4);glb.writeUInt32LE(glb.length,8);glb.writeUInt32LE(json.length,12);glb.writeUInt32LE(0x4e4f534a,16);json.copy(glb,20);let at=20+json.length;glb.writeUInt32LE(binary.length,at);glb.writeUInt32LE(0x004e4942,at+4);binary.copy(glb,at+8);assert.equal(inspectCharacterAsset(glb.buffer.slice(glb.byteOffset,glb.byteOffset+glb.byteLength),[],meta).primitives.length,1);
const {mkdtempSync,writeFileSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const {execFileSync}=await import('node:child_process');const {createHash}=await import('node:crypto');const dir=mkdtempSync(join(tmpdir(),'rally-intake-')),file=join(dir,'fixture.glb'),provenance=join(dir,'provenance.json');writeFileSync(file,glb);writeFileSync(provenance,JSON.stringify({...meta,sha256:createHash('sha256').update(glb).digest('hex')}));const cli=JSON.parse(execFileSync(process.execPath,['tools/inspect-character.mjs',file,provenance],{encoding:'utf8'}));assert.equal(cli.primitives[0].vertices,3);writeFileSync(provenance,JSON.stringify(meta));assert.throws(()=>execFileSync(process.execPath,['tools/inspect-character.mjs',file,provenance],{stdio:'pipe'}));console.log('Valid GLB JSON/BIN container and provenance CLI pass; mismatched source hash is rejected.');
