import assert from 'node:assert/strict';
import {GameClock} from '../dist/core/GameClock.js';
import {RelationshipSystem} from '../dist/simulation/RelationshipSystem.js';
import {ScheduleSystem} from '../dist/simulation/ScheduleSystem.js';
import {DailyGoalsSystem} from '../dist/simulation/DailyGoalsSystem.js';
import {ClubLifeSystem} from '../dist/simulation/ClubLifeSystem.js';
import {Navigation} from '../dist/world/Navigation.js';
import {Vec3} from '../dist/rendering/Math3D.js';
import {BallPhysics} from '../dist/tennis/BallPhysics.js';
import {Character,locomotionStyleFor} from '../dist/entities/Character.js';
import {RallySystem} from '../dist/tennis/RallySystem.js';
import {EmergentSocialSystem} from '../dist/simulation/EmergentSocialSystem.js';
import {migrateGameSave} from '../dist/persistence/migrations.js';
import {sampleClip} from '../dist/animation/ClipLibrary.js';
import {skinMatrices,BONE_COUNT,CHARACTER_SKIN} from '../dist/animation/CharacterSkin.js';
import {orthographic,sunViewProjection,transformPoint} from '../dist/rendering/Math3D.js';
import {CameraController} from '../dist/rendering/CameraController.js';
import {World} from '../dist/world/World.js';
import {memberData,destinations,palette,schedules} from '../dist/content/content.js';

let passed=0;
const test=(name,fn)=>{try{fn();console.log(`✓ ${name}`);passed++;}catch(e){console.error(`✗ ${name}`);throw e;}};

test('GameClock advances deterministically and wraps days',()=>{const c=new GameClock(1439.8,2);c.speed=2;c.update(.1);assert.ok(c.day>=2);c.update(1);assert.equal(c.day,3);assert.ok(c.minutes>=0&&c.minutes<1440)});
test('GameClock pause freezes time',()=>{const c=new GameClock(500,1);c.paused=true;c.update(10);assert.equal(c.minutes,500)});
test('Relationships change only requested member',()=>{const r=new RelationshipSystem();const before=r.get('mika').familiarity;r.interact('mika','coach',3,'worked through a focused forehand block');assert.ok(r.get('mika').familiarity>before);assert.equal(r.get('leo').familiarity,10);assert.match(r.get('mika').memories[0],/Day 3/)});
test('Relationship tier grows with repeated meaningful interaction',()=>{const r=new RelationshipSystem();for(let i=0;i<11;i++)r.interact('mika','matcha',1);assert.ok(['Club friend','Close friend','Trusted person'].includes(r.label('mika')))});
test('Schedule selects the latest due activity',()=>{let dest='';const s=new ScheduleSystem({mika:[{start:500,destination:'desk',activity:'check in'},{start:540,destination:'court',activity:'lesson'}]});const p={id:'mika',currentScheduleIndex:-1,setDestination:(d)=>dest=d};s.update(p,550);assert.equal(dest,'court')});
test('Daily intentions are finite, claim once, and reset by day',()=>{const d=new DailyGoalsSystem(1);for(const g of d.goals)d.record(g.kind);assert.equal(d.complete,true);const reward=d.claim();assert.ok(reward>0);assert.equal(d.claim(),0);d.ensureDay(2);assert.equal(d.complete,false);assert.equal(d.doneCount,0)});
test('Club-life moment fires once and persists to scrapbook',()=>{const life=new ClubLifeSystem();const m=life.update(1,575);assert.ok(m);assert.equal(m.title,'A clean one');assert.equal(life.update(1,575),null);assert.match(life.memories[0],/A clean one/);const save=life.serialize();const copy=new ClubLifeSystem();copy.load(save);assert.equal(copy.update(1,575),null)});
test('Navigation routes around a blocking rectangle',()=>{const n=new Navigation([{x:0,z:0,w:2,d:2}]);const p=n.path(new Vec3(-3,0,0),new Vec3(3,0,0));assert.ok(p.length>1);assert.ok(p.every(v=>!n.isBlocked(v.x,v.z)))});
test('Ballistic tennis ball bounces instead of teleporting',()=>{const b=new BallPhysics();b.launch(new Vec3(0,1,-4),new Vec3(.5,.1,4),.9);let bounced=false;let prev=b.position.clone();for(let i=0;i<180&&b.active;i++){const e=b.update(1/120);if(e.bounced)bounced=true;assert.ok(Math.hypot(b.position.x-prev.x,b.position.y-prev.y,b.position.z-prev.z)<.3);prev=b.position.clone()}assert.ok(bounced)});

test('Tennis racket contact releases the ball after the stroke begins, not on trigger',()=>{const nav=new Navigation();const dest={n:new Vec3(1,0,-5),s:new Vec3(1,0,5)};const spec=(id)=>({id,name:id,role:'member',shirt:'#888888',skin:'#c99977',hair:'#333333',playStyle:'test',goal:'test'});const n=new Character(spec('n'),dest.n,nav,dest),so=new Character(spec('s'),dest.s,nav,dest);const rally=new RallySystem(n,so);rally.start();for(let i=0;i<20;i++){n.update(1/120);so.update(1/120);rally.update(1/120)}assert.equal(rally.ball.active,false);for(let i=0;i<70&&!rally.ball.active;i++){n.update(1/120);so.update(1/120);rally.update(1/120)}assert.equal(rally.ball.active,true);assert.ok(n.animTime>=n.shotContactTime('serve'))});
test('Net collision ends the flight instead of bouncing backward through the rally',()=>{const b=new BallPhysics();b.position.set(0,.5,-.05);b.velocity.set(0,0,2);b.active=true;b.lastZ=-.05;const e=b.update(.05);assert.equal(e.net,true);assert.equal(b.active,false)});

test('Walking uses a planted stance foot while the root keeps moving',()=>{const nav=new Navigation();const dest={goal:new Vec3(0,0,5)};const spec={id:'walker',name:'Walker',role:'member',shirt:'#888888',skin:'#c99977',hair:'#333333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(0,0,0),nav,dest);c.goTo(dest.goal,'idle');let anchor=null,rootAtAnchor=0,verified=false;for(let i=0;i<240;i++){c.update(1/120);const k=c.debugKinematics();if(k.leftFootPlanted){if(!anchor){anchor=k.leftFoot.clone();rootAtAnchor=c.position.z;}else if(c.position.z-rootAtAnchor>.06){assert.ok(Vec3.sub(k.leftFoot,anchor).len()<.025);verified=true;break;}}else anchor=null;}assert.ok(verified)});
test('Court shuffle alternates planted feet instead of skating both shoes',()=>{const nav=new Navigation();const spec={id:'shuffle',name:'Shuffle',role:'member',shirt:'#888888',skin:'#c99977',hair:'#333333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(0,0,0),nav,{});c.moveOnCourt(new Vec3(2.2,0,0),new Vec3(0,0,-5));let sawLeft=false,sawRight=false;for(let i=0;i<180;i++){c.update(1/120);const k=c.debugKinematics();sawLeft ||= k.leftFootPlanted;sawRight ||= k.rightFootPlanted;}assert.ok(sawLeft&&sawRight)});
test('Shot IK brings the racket sweet spot to the requested contact point',()=>{const nav=new Navigation();const spec={id:'striker',name:'Striker',role:'member',shirt:'#888888',skin:'#c99977',hair:'#333333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(0,0,0),nav,{});c.face(new Vec3(0,0,5));for(let i=0;i<30;i++)c.update(1/120);c.setIncomingContact(new Vec3(.72,1.05,.52));c.triggerShot('swingForehand',new Vec3(0,.1,5));const contact=c.shotContactTime('swingForehand');for(let t=0;t<contact;t+=1/240)c.update(Math.min(1/240,contact-t));const k=c.debugKinematics();assert.ok(k.contactTarget);assert.ok(k.contactError<.035,`contact error ${k.contactError}`);assert.ok(Vec3.sub(k.racketGrip,k.racketCenter).len()>.25)});
test('Animation state changes blend instead of snapping instantly',()=>{const nav=new Navigation();const spec={id:'blend',name:'Blend',role:'member',shirt:'#888888',skin:'#c99977',hair:'#333333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(),nav,{});c.trigger('talk');const first=c.debugKinematics();assert.ok(first.transition<.05);c.update(.08);const mid=c.debugKinematics();assert.ok(mid.transition>0&&mid.transition<1);c.update(.3);assert.equal(c.debugKinematics().transition,1)});


test('Semantic memories retain people, tags and meaning',()=>{const r=new RelationshipSystem();r.interact('mika','coach',4,'worked on earlier preparation');const e=r.recall('mika','coach');assert.ok(e);assert.deepEqual(e.people,['player','mika']);assert.ok(e.tags.includes('learning'));assert.equal(e.day,4);assert.match(e.detail,/earlier preparation/)});
test('Pair relationships change autonomous social behavior without altering player relationship',()=>{const r=new RelationshipSystem();const playerBefore=r.get('mika').familiarity;for(let i=0;i<4;i++)r.interactBetween('mika','leo','rally',2,`rally ${i}`);assert.equal(r.get('mika').familiarity,playerBefore);assert.ok(r.getBetween('mika','leo').familiarity>10);assert.ok(r.behaviorBias('mika','leo').seekCompany>.1)});
test('Emergent social system creates state-driven rally opportunity',()=>{const r=new RelationshipSystem();const e=new EmergentSocialSystem(r);const event=e.update({day:1,minute:560,weather:'clear',busy:new Set(),lessonActive:false,courtBusy:false,mikaProgress:35});assert.ok(event);assert.equal(event.key,'mika-leo-rally');assert.ok(event.tags.includes('emergent'))});
test('Rain changes emergent social choice when court friends are busy',()=>{const r=new RelationshipSystem();const e=new EmergentSocialSystem(r);const event=e.update({day:1,minute:560,weather:'rain',busy:new Set(['mika','leo']),lessonActive:false,courtBusy:true,mikaProgress:35});assert.ok(event);assert.equal(event.key,'rain-tea')});
test('Court movement exposes lateral locomotion blend after split step',()=>{const nav=new Navigation();const spec={id:'blendcourt',name:'Blend',role:'member',shirt:'#888',skin:'#c99',hair:'#333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(0,0,0),nav,{});c.face(new Vec3(0,0,-5));for(let i=0;i<20;i++)c.update(1/120);c.moveOnCourt(new Vec3(2,0,0),new Vec3(0,0,-5));let sawSplit=false,sawLateral=false;for(let i=0;i<160;i++){c.update(1/120);const k=c.debugKinematics();sawSplit ||= k.courtPhase==='split';sawLateral ||= k.motionBlend.lateral>.18;}assert.ok(sawSplit);assert.ok(sawLateral)});
test('Lucresia development changes preparation timing and tennis skill',()=>{const nav=new Navigation();const spec={id:'mika',name:'Lucresia',role:'member',shirt:'#888',skin:'#c99',hair:'#333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(),nav,{});c.setDevelopment(20);const lowSkill=c.tennisSkill(),lowTime=c.shotContactTime('swingForehand');c.setDevelopment(80);assert.ok(c.tennisSkill()>lowSkill);assert.ok(c.shotContactTime('swingForehand')>lowTime)});
test('Serve toss hand rises before racket contact',()=>{const nav=new Navigation();const spec={id:'server',name:'Server',role:'member',shirt:'#888',skin:'#c99',hair:'#333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(),nav,{});c.face(new Vec3(0,0,5));for(let i=0;i<20;i++)c.update(1/120);c.triggerShot('serve',new Vec3(0,.1,5));const start=c.serveTossPoint().y;for(let i=0;i<22;i++)c.update(1/120);const raised=c.serveTossPoint().y;assert.ok(raised>start+.12,`${start} -> ${raised}`)});
test('Racket vibration is triggered by impact then decays',()=>{const nav=new Navigation();const spec={id:'impact',name:'Impact',role:'member',shirt:'#888',skin:'#c99',hair:'#333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(),nav,{});c.notifyRacketImpact('frame');const start=c.debugKinematics().racketVibration;assert.ok(start>1);for(let i=0;i<40;i++)c.update(1/120);assert.ok(c.debugKinematics().racketVibration<start*.3)});
test('Version 3 saves migrate semantic-memory fields without losing old relationship text',()=>{const old={clock:{minutes:540,day:2,paused:false,speed:1},coins:10,stars:2,coachXP:14,mikaProgress:30,weather:'clear',placements:[],relationships:{mika:{familiarity:22,warmth:20,trust:16,rivalry:0,memories:['Day 1 · hello']}},equipment:{frame:'Cedar 98',tension:52,string:'Soft poly'},player:{x:0,z:0}};const s=migrateGameSave(3,old);assert.equal(s.relationships.mika.memories[0],'Day 1 · hello');assert.deepEqual(s.relationships.mika.events,[]);assert.equal(s.bestRally,0)});


test('Authored locomotion clip contains a real swing-foot lift arc',()=>{const a=sampleClip('walk',0),b=sampleClip('walk',.25),c=sampleClip('walk',.5);assert.ok(b.footL.y>a.footL.y+.03);assert.ok(c.footR.y>=a.footR.y)});
test('Skeletal skin pipeline produces finite matrices for all fifteen bones',()=>{const rig={pelvis:new Vec3(0,.79,0),spine:new Vec3(0,1.05,.01),chest:new Vec3(0,1.34,.015),neck:new Vec3(0,1.56,.01),head:new Vec3(0,1.78,.01),upperArmL:new Vec3(-.37,1.34,.015),foreArmL:new Vec3(-.49,1.12,.01),handL:new Vec3(-.50,.94,.01),upperArmR:new Vec3(.37,1.34,.015),foreArmR:new Vec3(.49,1.12,.01),handR:new Vec3(.50,.94,.01),thighL:new Vec3(-.16,.76,0),shinL:new Vec3(-.17,.43,.04),footL:new Vec3(-.17,.11,.08),thighR:new Vec3(.16,.76,0),shinR:new Vec3(.17,.43,.04),footR:new Vec3(.17,.11,.08),forward:new Vec3(0,0,1)};const m=skinMatrices(rig);assert.equal(m.length,BONE_COUNT*16);assert.ok([...m].every(Number.isFinite));});
test('Characters now emit GPU-skinned body surfaces instead of only rigid limb cylinders',()=>{const nav=new Navigation();const spec={id:'skin-test',name:'Skin Test',role:'member',shirt:'#889988',skin:'#c99a77',hair:'#333',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(),nav,{});const items=c.meshes(false);const skins=items.filter(x=>'skin' in x);assert.equal(skins.length,3);assert.ok(CHARACTER_SKIN.top.positions.length>300);assert.ok(CHARACTER_SKIN.arms.boneWeights.length===CHARACTER_SKIN.arms.boneIndices.length);});

// --- v7: lighting and framing ---
test('Orthographic projection maps the frustum corners onto clip space',()=>{const m=orthographic(-2,2,-3,3,1,11);const c=transformPoint(m,new Vec3(2,3,-11));assert.ok(Math.abs(c.x-1)<1e-5);assert.ok(Math.abs(c.y-1)<1e-5);assert.ok(Math.abs(c.z-1)<1e-5);const n=transformPoint(m,new Vec3(-2,-3,-1));assert.ok(Math.abs(n.x+1)<1e-5);assert.ok(Math.abs(n.y+1)<1e-5);assert.ok(Math.abs(n.z+1)<1e-5)});
test('Sun matrix keeps the whole academy inside the shadow map for every sun angle',()=>{const centre=new Vec3(-.4,1.5,-1),R=17.0;const corners=[];for(const x of [-13,12])for(const y of [0,4.6])for(const z of [-10.5,8])corners.push(new Vec3(x,y,z));for(let h=6;h<=20;h+=.5){const t=Math.max(0,Math.min(1,(h-6)/13));const az=-1+t*1.6,el=.34+Math.sin(Math.PI*t)*.8;const sun=new Vec3(-Math.sin(az)*Math.cos(el),-Math.sin(el),-Math.cos(az)*Math.cos(el));const vp=sunViewProjection(sun,centre,R,2048);for(const c of corners){const p=transformPoint(vp,c);assert.ok(Math.abs(p.x)<=1.001&&Math.abs(p.y)<=1.001&&p.z<=1.001,`hour ${h} corner escaped the shadow frustum`)}}});
test('Sun matrix snaps to whole texels so shadow edges do not crawl',()=>{const a=sunViewProjection(new Vec3(-.3,-.8,-.5),new Vec3(0,1,0),17.0,2048);const b=sunViewProjection(new Vec3(-.3001,-.8,-.5),new Vec3(0,1,0),17.0,2048);let diff=0;for(let i=0;i<16;i++)diff=Math.max(diff,Math.abs(a[i]-b[i]));assert.ok(diff<.01,'a tiny sun nudge should not jump the shadow frustum')});
test('Camera frames the whole club in landscape and stays readable in portrait',()=>{const stub={getBoundingClientRect:()=>({left:0,top:0,width:100,height:100})};const wide=new CameraController(stub);wide.setAspect(16/9);const tall=new CameraController(stub);tall.setAspect(390/844);
  const halfWidth=(c)=>c.fitDistance*Math.tan(c.fov/2)*c.aspect;
  assert.ok(halfWidth(wide)>=12.2,`landscape only frames ${halfWidth(wide).toFixed(1)} units of club`);
  assert.ok(halfWidth(tall)>=9.0,`portrait only frames ${halfWidth(tall).toFixed(1)} units of club`);
  assert.ok(tall.fov>wide.fov,'portrait needs the wider lens');
  assert.ok(tall.fitDistance<=86&&wide.fitDistance<=86)});
test('Zooming disables auto framing and frameAcademy restores it',()=>{const stub={getBoundingClientRect:()=>({left:0,top:0,width:100,height:100})};const c=new CameraController(stub);c.setAspect(16/9);assert.equal(c.autoFrame,true);c.zoom(-6);assert.equal(c.autoFrame,false);assert.ok(c.desiredDistance<c.fitDistance);c.frameAcademy();assert.equal(c.autoFrame,true);assert.equal(c.desiredDistance,c.fitDistance)});
test('Zoom stays inside its bounds however hard the player scrolls',()=>{const stub={getBoundingClientRect:()=>({left:0,top:0,width:100,height:100})};const c=new CameraController(stub);c.setAspect(16/9);for(let i=0;i<400;i++)c.zoom(-9);assert.ok(c.desiredDistance>=c.minDistance-1e-6);for(let i=0;i<400;i++)c.zoom(9);assert.ok(c.desiredDistance<=c.maxDistance+1e-6)});



// --- v8: boutique diorama art direction ---
test('World exposes a real material hierarchy instead of one flat shading class',()=>{const w=new World();const kinds=new Set(w.meshes.map(m=>m.material).filter(Boolean));for(const k of ['court','wood','fabric','ceramic','leaf'])assert.ok(kinds.has(k),`missing material ${k}`)});
test('Bonsai is a repeated Rally House signature rather than a single green blob',()=>{const w=new World();const leaves=w.meshes.filter(m=>m.material==='leaf');const ceramics=w.meshes.filter(m=>m.material==='ceramic');assert.ok(leaves.length>=20,`only ${leaves.length} authored leaf masses`);assert.ok(ceramics.length>=10,`only ${ceramics.length} ceramic/pot pieces`);const areas=[[-8.22,4.48],[-10.58,-8.91],[7.06,4.58],[10.62,-7.04],[10.2,3.9]];for(const [x,z] of areas)assert.ok(leaves.some(m=>Math.hypot(m.position.x-x,m.position.z-z)<1.4),`no bonsai foliage near ${x},${z}`)});
test('Core women have distinct adult visual signatures',()=>{const by=Object.fromEntries(memberData.map(m=>[m.id,m]));assert.equal(by.mika.hairStyle,'ponytail');assert.equal(by.mika.outfit,'skirt');assert.equal(by.coach.hairStyle,'bun');assert.equal(by.coach.outfit,'skort');assert.equal(by.nia.hairStyle,'bob');assert.equal(by.nia.outfit,'host');for(const id of ['mika','coach','nia'])assert.equal(by[id].presentation,'feminine')});
test('Lucresia emits stylized outfit and hair geometry without breaking the hybrid skeleton',()=>{const spec=memberData.find(m=>m.id==='mika');const c=new Character(spec,destinations.courtSouth,new Navigation(),destinations);const items=c.meshes(false);assert.equal(items.filter(x=>'skin' in x).length,3);assert.ok(items.some(x=>!('skin' in x)&&x.kind==='cone'),'skirt silhouette missing');assert.ok(items.filter(x=>!('skin' in x)&&x.kind==='sphere'&&x.material==='hair').length>=3,'ponytail layering missing')});
test('Bonsai leaf motion stays subtle and finite',()=>{const w=new World();const a=w.dynamicMeshes(2,600,new Vec3(20,12,20));const b=w.dynamicMeshes(2.5,600,new Vec3(20,12,20));const la=a.filter(m=>m.material==='leaf'&&m.position.x>9.5&&m.position.z>3.2);const lb=b.filter(m=>m.material==='leaf'&&m.position.x>9.5&&m.position.z>3.2);assert.equal(la.length,5);assert.equal(lb.length,5);for(let i=0;i<5;i++){const d=Vec3.sub(la[i].position,lb[i].position).len();assert.ok(d<.08&&Number.isFinite(d))}});



// --- v9: color energy, character charm and locomotion polish ---
const rgb=(h)=>{const s=h.replace('#','');return [0,2,4].map(i=>parseInt(s.slice(i,i+2),16)/255)};
test('v9 palette lifts the academy out of the grey-beige midtone band',()=>{const cream=rgb(palette.cream),court=rgb(palette.court),peach=rgb(palette.peach);assert.ok(cream.reduce((a,b)=>a+b,0)/3>.90,'cream should read bright');assert.ok(Math.max(...court)-Math.min(...court)>.12,'court green should retain chroma');assert.ok(Math.max(...peach)-Math.min(...peach)>.20,'peach accent should be visibly warm')});
test('Core cast now carries distinct eye and outfit color signatures',()=>{const by=Object.fromEntries(memberData.map(m=>[m.id,m]));assert.ok(by.mika.eye&&by.coach.eye&&by.nia.eye);assert.notEqual(by.mika.eye,by.coach.eye);assert.notEqual(by.nia.shirt,by.mika.shirt);assert.ok(by.mika.accent.startsWith('#')&&by.nia.accent.startsWith('#'))});
test('Locomotion personalities change more than playback speed',()=>{const june=locomotionStyleFor('coach'),mika=locomotionStyleFor('mika'),nia=locomotionStyleFor('nia'),leo=locomotionStyleFor('leo');assert.ok(mika.bounce>june.bounce);assert.ok(mika.armSwing>june.armSwing);assert.ok(leo.stride>nia.stride);assert.notEqual(june.torsoCounter,mika.torsoCounter)});
test('Re-authored walk has explicit passing and lift poses',()=>{const contact=sampleClip('walk',0),pass=sampleClip('walk',.25),opposite=sampleClip('walk',.5);assert.ok(pass.footL.y>contact.footL.y+.06);assert.ok(pass.pelvisY>contact.pelvisY+.015);assert.ok(opposite.footR.z>contact.footR.z+.10)});
test('Path locomotion eases into travel instead of teleporting to full speed',()=>{const nav=new Navigation();const spec={id:'mika',name:'Lucresia',role:'member',shirt:'#f0a078',skin:'#cf9270',hair:'#473029',playStyle:'test',goal:'test'};const c=new Character(spec,new Vec3(),nav,{goal:new Vec3(0,0,5)});c.goTo(new Vec3(0,0,5),'idle');const z0=c.position.z;c.update(1/60);const first=c.position.z-z0;for(let i=0;i<30;i++)c.update(1/60);const z1=c.position.z;c.update(1/60);const later=c.position.z-z1;assert.ok(first<later*.65,`${first} should be clearly below cruising step ${later}`);assert.ok(first>0)});
test('Barbara emits boutique clothing accents without adding a racket',()=>{const spec=memberData.find(m=>m.id==='nia');const c=new Character(spec,destinations.lounge,new Navigation(),destinations);const items=c.meshes(false).filter(x=>!('skin' in x));assert.ok(items.some(x=>x.kind==='torus'&&x.material==='fabric'),'collar accent missing');assert.ok(items.filter(x=>x.kind==='cylinder'&&x.material==='fabric').length>=2,'sock accents missing')});

console.log(`\n${passed} simulation checks passed.`);
