import type { Metadata } from "next";
import Link from "next/link";
import { CommandMap, EscalationLadder, ProcessFlow, RecoveryGates, RedundancyMap, RiskMatrix } from "@/components/SystemVisuals";

export const metadata: Metadata = {
  title: "Emergency Operations at Sonoma — Academic Systems Study",
  description: "A Belmont Abbey College academic study of role-based emergency coordination for the 2026 Toyota/Save Mart 350 at Sonoma Raceway.",
  alternates: { canonical: "/work/sonoma-emergency-operations" },
  openGraph: { title: "Designing an emergency system for a complex race weekend", description: "An evidence-labeled academic study in race emergency planning and motorsport risk management.", url: "/work/sonoma-emergency-operations" },
};

const scenarios = ["High-energy crash", "Heat / medical surge", "Fire or hazardous material", "Wildfire / severe weather", "Security threat", "Communications / utility failure"];

export default function SonomaEmergencyOperations() {
  return <article className="case-study">
    <header className="case-study-hero"><div className="shell"><div className="case-breadcrumb"><Link href="/motorsport">Motorsport</Link><span>/</span><span>Emergency operations</span></div><div className="case-title-grid"><div><p className="overline"><span /> Motorsport medicine / risk management</p><h1>Designing an emergency system for a complex race weekend.</h1><p className="case-deck">A role-based proposal for preserving coordination across race control, rescue, medical, security, operations, public information, and external mutual aid.</p></div><aside><span className="status status-gold">ACADEMIC STUDY</span><dl><dt>Institution</dt><dd>Belmont Abbey College</dd><dt>Course</dt><dd>MM 685: Risk Management in Motorsport</dd><dt>Source</dt><dd>Assignment 6 · July 2026</dd><dt>Context</dt><dd>2026 Toyota/Save Mart 350 at Sonoma Raceway</dd></dl></aside></div></div></header>

    <section className="case-disclaimer"><div className="shell"><strong>Scope and authority</strong><p>This was an academic, role-based proposal. It was not an official Sonoma Raceway or NASCAR emergency plan. Operational use would require reconciliation with current sanctioning-body procedures, venue plans, public-safety protocols, hospital agreements, communications systems, credentialing rules, and lawful agency authority.</p></div></section>

    <div className="shell case-body">
      <section className="case-section"><div className="case-section-label"><span>01</span><p>Problem</p></div><div className="case-section-content"><h2>Many disciplines. One incident clock.</h2><p className="lead">A major road-course race weekend can create simultaneous demands on rescue, medical care, race control, security, public safety, communications, and event continuity. The design problem is not only whether each function can respond. It is whether authority, information, and handoffs remain coherent when conditions change.</p></div></section>

      <section className="case-section"><div className="case-section-label"><span>02</span><p>Planning environment</p></div><div className="case-section-content"><h2>A venue is an operating system.</h2><p>The study used the public facility map and venue information to frame a 1.99-mile road course with more than 160 feet of elevation change, dispersed hillside seating, pit and garage operations, campgrounds, a heliport, and a population across State Route 121. It grouped the venue into five planning zones so access, crowd movement, communications, and medical response could be reasoned about by location.</p><div className="constraint-grid"><span>West ingress</span><span>Competition core</span><span>North hillside</span><span>East hillside</span><span>50 Acres</span><span>Protected responder access</span></div><p className="source-line">Venue characteristics are those cited in the course paper from Sonoma Raceway public materials. Private routes, staffing, agreements, and contacts are not reproduced.</p></div></section>

      <section className="case-section"><div className="case-section-label"><span>03</span><p>Design objective</p></div><div className="case-section-content"><h2>Protect life. Preserve coordination.</h2><p>The proposal structures medical, rescue, security, public-information, and operational work around a shared operating picture. It does not grant authority; it makes the required interfaces visible so that lawful plans and responsible agencies can be reconciled before an event.</p></div></section>

      <section className="case-section case-section-wide"><div className="case-section-label"><span>04</span><p>System architecture</p></div><div className="case-section-content"><h2>Command is a relationship, not a box.</h2><CommandMap /><p className="source-line">Portfolio abstraction of the role-based proposal. It is not a Sonoma Raceway staffing chart.</p></div></section>

      <section className="case-section"><div className="case-section-label"><span>05</span><p>Escalation</p></div><div className="case-section-content"><h2>Scale coordination with consequence.</h2><p>The paper classifies incidents by consequence and coordination need—not visual drama alone—and calls for reassessment as conditions change. The levels below are the author’s academic proposal, not Sonoma Raceway or NASCAR classifications.</p><EscalationLadder /></div></section>

      <section className="case-section case-section-wide"><div className="case-section-label"><span>06</span><p>Scenario planning</p></div><div className="case-section-content"><h2>Test the interfaces, not only the hazards.</h2><p>The course-use proposal modeled six incident families. Each exposes a different coordination failure mode.</p><ul className="scenario-tags">{scenarios.map((scenario) => <li key={scenario}>{scenario}</li>)}</ul><RiskMatrix /></div></section>

      <section className="case-section"><div className="case-section-label"><span>07</span><p>Medical workflow</p></div><div className="case-section-content"><h2>Preserve the chain from scene to disposition.</h2><ProcessFlow label="Proposed medical handoff pipeline" steps={[{label:"Incident",note:"location, vehicle, visible hazards"},{label:"Scene stabilization",note:"fire, vehicle, and access hazards controlled"},{label:"Medical access",note:"course status and safe route confirmed"},{label:"Triage",note:"life threats before neurotrauma screening"},{label:"Structured handoff",note:"mechanism, protection, findings, treatment, times"},{label:"Transport decision",note:"mode, receiving capability, remaining coverage"},{label:"Recovery + reporting",note:"track, systems, records, and readiness checked"}]} /><p className="source-line">Abstracted from section 7.1 and appendices A–C of the course paper. It is not clinical guidance or a venue procedure.</p></div></section>

      <section className="case-section"><div className="case-section-label"><span>08</span><p>Communications</p></div><div className="case-section-content"><h2>Redundancy must end in confirmation.</h2><p>The proposal treats plain language, location specificity, read-back, protected medical traffic, and time logging as one closed-loop system. Backup methods matter only when the receiving role confirms the message.</p><RedundancyMap /><ProcessFlow label="Proposed evacuation / shelter decision flow" steps={[{label:"Locate the hazard",note:"direction, spread, and affected zone"},{label:"Confirm authority",note:"event command or lawful public agency"},{label:"Test movement",note:"road capacity, responder access, mobility needs"},{label:"Test shelter",note:"validated protection and safe duration"},{label:"Choose action",note:"phased evacuation, shelter, or hybrid"},{label:"Account",note:"sweep zones and reconcile people"}]} /></div></section>

      <section className="case-section"><div className="case-section-label"><span>09</span><p>Recovery gates</p></div><div className="case-section-content"><h2>Response does not end when the hazard stops.</h2><p>Return to operations requires explicit checks for people, medical continuity, systems, authority, and documentation.</p><RecoveryGates /></div></section>

      <section className="case-section limitations-section"><div className="case-section-label"><span>10</span><p>Constraints</p></div><div className="case-section-content"><h2>What this study does not establish.</h2><ul><li>No operational validation, exercise result, implementation outcome, or measured performance.</li><li>No Sonoma Raceway, NASCAR, hospital, public-safety, or sanctioning-body approval.</li><li>No claim of credentialing, clinical authority, trackside responsibility, or professional appointment.</li><li>Numeric heat triggers and medical-resource thresholds in the paper are proposals requiring local validation; they are not published here as operating criteria.</li><li>No private staffing, radio assignment, contact, hospital agreement, or agency-authority detail is reproduced.</li></ul><p className="source-line">Primary source reviewed: Arjan Puniani, <em>Emergency and Disaster Planning: 2026 Toyota/Save Mart 350 at Sonoma Raceway</em>, Belmont Abbey College, MM 685, Assignment 6, July 13, 2026, pp. 1–13.</p></div></section>

      <footer className="case-next"><p>Continue through the motorsport system</p><Link href="/work/motorsport-neurotrauma-toolkit"><strong>Next: crash mechanism to medical handoff</strong><span>↗</span></Link></footer>
    </div>
  </article>;
}
