import type { Metadata } from "next";
import Link from "next/link";
import { ReasonOSLab } from "@/components/ReasonOSLab";
import { siteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Vector EKG and ReasonOS | Inspectable ECG Reasoning",
  description: "Arjan Singh Puniani's educational prototype for recording ECG observations, measurements, competing explanations, contradictions, provenance, and revisions.",
  alternates: { canonical: "/work/vector-ekg-reasonos" },
  openGraph: { title: "Vector EKG and ReasonOS", description: "An inspectable reasoning architecture applied to electrocardiography.", url: `${siteUrl}/work/vector-ekg-reasonos`, type: "article" },
};

const evidenceStates = [
  ["Observed", "Directly marked or measured from the source."], ["Inferred", "Derived from recorded observations under an explicit rule."],
  ["Contradicted", "Conflicts with another admitted finding."], ["Unresolved", "Evidence is insufficient or discordant."],
  ["Excluded", "A candidate explanation fails a required criterion."], ["Confirmed", "A defined review process supports the claim. Not used for diagnosis here."],
] as const;

function Flow({ items, label }: { items: string[]; label: string }) {
  return <div className="technical-flow" role="img" aria-label={label}>{items.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong>{index < items.length - 1 && <i aria-hidden="true">→</i>}</div>)}</div>;
}

export default function VectorEkgReasonOSPage() {
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Vector EKG and ReasonOS", applicationCategory: "EducationalApplication", operatingSystem: "Web", author: { "@type": "Person", name: "Arjan Singh Puniani", url: siteUrl }, url: `${siteUrl}/work/vector-ekg-reasonos`, description: "Educational research prototype for inspectable ECG reasoning.", isAccessibleForFree: true };
  return <div className="vector-case">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}/>
    <header className="vector-hero"><div className="shell"><p className="eyebrow">Reasoning systems · Electrocardiography · 2026</p><h1>Make the reasoning inspectable.</h1><p className="vector-deck">ReasonOS records how evidence changes a model. Vector EKG applies that architecture to electrocardiographic interpretation.</p><div className="actions"><a className="button" href="#laboratory">Run the synthetic laboratory</a><a className="button-secondary" href="#specification">Read the specification</a></div><dl className="vector-facts"><div><dt>Status</dt><dd>Tested educational prototype</dd></div><div><dt>Role</dt><dd>Product designer and developer</dd></div><div><dt>Clinical use</dt><dd>None</dd></div></dl></div></header>

    <section className="section"><div className="shell case-intro"><p className="eyebrow">The problem</p><div><h2>An answer does not reveal how the learner reached it.</h2><p>Conventional ECG exercises preserve the final interpretation and discard the path. They cannot distinguish a missed region from a faulty measurement, an unsupported inference, or a contradiction the learner never tested.</p><p>ReasonOS treats that path as data. Each attempted change records its inputs, actor, evidence, provenance, constraint results, acceptance state, and revision lineage. Rejected attempts remain reviewable.</p></div></div></section>

    <section className="section technical-surface" aria-labelledby="architecture-heading"><div className="shell"><p className="eyebrow">Architecture</p><h2 id="architecture-heading">Domain meaning stays outside the kernel.</h2><Flow label="Input evidence passes through observation extraction into a structured evidence graph, competing hypotheses, contradiction checks, confidence updates, a reasoning timeline, and human review." items={["Input evidence", "Observation", "Evidence graph", "Competing paths", "Constraint check", "Trace", "Human review"]}/><p className="diagram-caption">The kernel manages immutable state and admissibility. The ECG plugin defines leads, calibration, measurements, candidate pathways, and domain constraints.</p></div></section>

    <section className="section"><div className="shell"><p className="eyebrow">Vector EKG pipeline</p><h2>Measurements retain their source and method.</h2><Flow label="Raw ECG passes through calibration and lead checks, measurements, axis interpretation, candidate explanations, discordance checks, and human review." items={["Raw ECG", "Calibration", "Intervals", "Axis", "Candidate explanation", "Discordance", "Review state"]}/><div className="method-grid"><article><span>01</span><h3>Separate witnesses</h3><p>Source data, learner selections, application calculations, and expert-authored references never silently change identity.</p></article><article><span>02</span><h3>Preserve failed attempts</h3><p>A rejected transformation enters the trace without creating a new accepted state.</p></article><article><span>03</span><h3>Compare coherent paths</h3><p>Weighted Jaccard comparison evaluates each versioned path independently. Candidate paths remain labeled unvalidated.</p></article></div></div></section>

    <section className="section technical-surface"><div className="shell"><p className="eyebrow">Synthetic reasoning trace</p><h2>Evidence can strengthen one explanation and weaken another.</h2><div className="trace-example" aria-label="Synthetic example showing a regular rhythm observation supporting a sinus pathway, a missing P wave observation creating a contradiction, and the hypothesis remaining unresolved"><article><span>Observed</span><strong>R–R intervals appear regular</strong><p>Supports a timing-led regular-rhythm path.</p></article><i>→</i><article><span>Inferred</span><strong>Regular narrow-complex rhythm</strong><p>Provisional. The source is one synthetic lead.</p></article><i>→</i><article className="contradiction"><span>Contradiction</span><strong>P-wave relation not established</strong><p>Blocks a stronger sinus-rhythm claim.</p></article><i>→</i><article><span>Unresolved</span><strong>Revise and retain uncertainty</strong><p>The trace keeps both the original claim and revision.</p></article></div><p className="diagram-caption">Synthetic educational example. It is not a patient interpretation or validated diagnostic workflow.</p></div></section>

    <section className="section"><div className="shell"><p className="eyebrow">Evidence-state model</p><h2>Uncertainty is a state, not missing interface polish.</h2><div className="evidence-state-grid">{evidenceStates.map(([state, meaning]) => <article key={state}><h3>{state}</h3><p>{meaning}</p></article>)}</div></div></section>

    <section className="section lab-embed" id="laboratory" data-analytics-event="open_reasoning_trace"><div className="shell"><p className="eyebrow">Executable vertical slice</p><h2>Inspect the event record yourself.</h2><p className="section-lede">The bundled waveform is synthetic. Select points, calculate an interval, derive frontal axis and corrected QT values, compare a candidate pathway, test a contradiction, and inspect the append-only trace.</p></div><div className="reasonos-theme"><ReasonOSLab/></div></section>

    <section className="section" id="specification"><div className="shell"><p className="eyebrow">Technical specification</p><h2>Current implementation boundary</h2><div className="spec-grid"><article><h3>Inputs</h3><ul><li>Synthetic ECG coordinates</li><li>Manual calibration metadata</li><li>Learner observations and measurements</li><li>Versioned candidate-path definitions</li></ul></article><article><h3>Outputs</h3><ul><li>Immutable accepted states</li><li>Accepted and rejected trace events</li><li>Application-calculated interval, axis, and QTc values</li><li>Candidate-path structural score</li></ul></article><article><h3>Invariants</h3><ul><li>Referenced inputs must exist</li><li>Writes are append-only</li><li>Actor and provenance are required</li><li>Causal ancestry remains acyclic</li><li>Witness identity is preserved</li></ul></article><article><h3>Known failure modes</h3><ul><li>Incorrect manual calibration</li><li>Poor source quality</li><li>Incompatible evidence combined across paths</li><li>Candidate models mistaken for expert consensus</li><li>Single-lead evidence overinterpreted</li></ul></article></div></div></section>

    <section className="section clinical-boundary"><div className="shell case-intro"><p className="eyebrow">Clinical boundary</p><div><h2>This system does not diagnose patients.</h2><p>Vector EKG is educational research software. It has no clinical validation, regulatory clearance, expert-trace reliability study, demonstrated learning benefit, or authorization for patient care.</p><p>Before clinical use, it would require a defined intended use, expert-reviewed ontology, representative datasets, human-factors testing, prospective validation, security and privacy controls, regulatory analysis, and independent clinical governance.</p><Link className="text-link" href="/research">See the documented research record →</Link></div></div></section>
  </div>;
}
