import Image from "next/image";
import Link from "next/link";

const chapters = [
  { number:"01", eyebrow:"System architecture", title:"Sense the event. Control the intervention.", body:"The proposed architecture links electrocorticography, temperature sensing, control logic, and localized thermoelectric cooling. These diagrams describe design intent, not a clinically validated implant.", panels:[
    {src:"/images/neurotechnology/seizefreeze/implant-architecture.webp",alt:"Concept diagram showing a proposed SeizeFreeze implant above the cortex with sensing, thermoelectric, and cooling layers",caption:"Proposed implant architecture and superficial cortical interface."},
    {src:"/images/neurotechnology/seizefreeze/closed-loop-control.webp",alt:"Block diagram of the proposed SeizeFreeze closed-loop sensing and cortical cooling control system",caption:"Conceptual event-triggered sensing and control loop."},
  ]},
  { number:"02", eyebrow:"Thermal model", title:"Move heat locally, then prove where it goes.", body:"A Peltier element can create a temperature gradient when current flows. Translation depends on heat rejection, perfusion, tissue conduction, contact geometry, and control limits. Simulation and bench testing must resolve those variables.", panels:[
    {src:"/images/neurotechnology/seizefreeze/thermoelectric-cooling.webp",alt:"Diagram of thermoelectric cooling physics with hot and cold sides of a Peltier element and the heat-removal equation",caption:"Simplified thermoelectric energy balance for the proposed interface."},
    {src:"/images/neurotechnology/seizefreeze/cortical-heat-transfer.webp",alt:"Conceptual cortical temperature field and bioheat-transfer equation beneath a localized cooling surface",caption:"Conceptual temperature field. Parameters and boundary conditions require validation."},
  ]},
  { number:"03", eyebrow:"Mechanism and safeguards", title:"Cooling is the mechanism. Control is the safety problem.", body:"Cooling can alter neuronal excitability through several interacting mechanisms. A useful device would need independent temperature limits, rapid shutdown, electrophysiologic confirmation, and protection against thermal overshoot or heat accumulation.", panels:[
    {src:"/images/neurotechnology/seizefreeze/biological-effects.webp",alt:"Diagram of proposed biological effects of cortical cooling on synaptic transmission, ion channels, neurotransmitter release, and network activity",caption:"Mechanistic rationale assembled from established physiology and preclinical evidence."},
    {src:"/images/neurotechnology/seizefreeze/safety-design.webp",alt:"Conceptual safety constraints and failure modes for a focal cortical cooling system",caption:"Draft safety framework. Numerical limits are provisional and require experimental validation."},
  ]},
  { number:"04", eyebrow:"Translation", title:"An implant is a system, not a rendering.", body:"Packaging must address hermeticity, corrosion, biocompatibility, electrical isolation, thermal efficiency, fixation, and surgical access. This stack is a starting point for design controls, not a finalized bill of materials.", panels:[
    {src:"/images/neurotechnology/seizefreeze/materials-packaging.webp",alt:"Exploded conceptual stack showing proposed housing, electronics, thermal spreader, thermoelectric module, insulation, cold plate, interface, and sensors",caption:"Candidate packaging stack and material-selection criteria."},
    {src:"/images/neurotechnology/seizefreeze/translational-positioning.webp",alt:"Evidence map separating established physiology, preclinical focal-cooling evidence, and the proposed SeizeFreeze implant architecture",caption:"Evidence boundary: established, preclinical, and proposed elements remain distinct."},
  ]},
];

export function SeizeFreezeCaseStudy(){return <article className="sf-case">
  <header className="sf-hero"><Image src="/images/neurotechnology/seizefreeze-homepage-hero-v2.webp" alt="Concept visualization of the proposed SeizeFreeze implant, thermoelectric assembly, and localized cortical cooling" fill priority sizes="100vw"/><div className="sf-hero-shade"/><div className="shell sf-hero-content"><p className="sf-kicker">01 / Neurotechnology · Investigational concept</p><h1>Seize<span>Freeze</span></h1><p className="sf-deck">Closed-loop focal cortical cooling for drug-resistant focal epilepsy.</p><dl className="sf-facts"><div><dt>Role</dt><dd>Founder + device lead</dd></div><div><dt>State</dt><dd>Concept + prototype planning</dd></div><div><dt>Recognition</dt><dd>$12.5K documented awards</dd></div><div><dt>Period</dt><dd>2022–present</dd></div></dl></div></header>
  <div className="sf-boundary"><div className="shell"><strong>Evidence boundary</strong><p>SeizeFreeze is a proposed engineering system. It has not undergone human testing, clinical validation, or regulatory review.</p></div></div>
  <section className="sf-opening sf-section"><div className="shell sf-opening-grid"><p className="sf-index">00 / The proposition</p><div><h2>What if seizure control could be local, reversible, and responsive?</h2><p className="sf-lede">The concept pairs seizure sensing with controlled cooling at a focal cortical target. The aim is to suppress pathological activity without removing tissue. The engineering work is translating that proposition into measurable thermal, electrical, mechanical, and biological requirements.</p></div></div></section>
  <section className="sf-film sf-section" aria-labelledby="sf-film-title"><div className="shell"><div className="sf-section-head"><div><p className="sf-index">Concept film / 02:17</p><h2 id="sf-film-title">The original vision</h2></div><p>An early design film that frames the unmet need and proposed system. Market figures and quantitative statements are historical project estimates, not current clinical or commercial evidence.</p></div><video className="sf-video" controls playsInline preload="metadata" poster="/images/neurotechnology/seizefreeze/concept-film-poster.webp" aria-describedby="sf-film-context"><source src="/video/seizefreeze-concept-film.mp4" type="video/mp4"/>Your browser does not support embedded video.</video><p id="sf-film-context" className="sf-film-note">Film context: drug-resistant focal epilepsy, the proposed closed-loop cooling concept, early device imagery, and the project mission. Audio is optional; the case study below contains the substantive engineering narrative.</p></div></section>
  {chapters.map(chapter=><section className="sf-chapter sf-section" key={chapter.number}><div className="shell"><div className="sf-chapter-intro"><p className="sf-index">{chapter.number} / {chapter.eyebrow}</p><div><h2>{chapter.title}</h2><p>{chapter.body}</p></div></div><div className="sf-panel-grid">{chapter.panels.map(panel=><figure className="sf-panel" key={panel.src}><a href={panel.src} target="_blank" rel="noreferrer" aria-label={`Open full-resolution figure: ${panel.caption}`}><Image src={panel.src} alt={panel.alt} width={1448} height={1086} sizes="(max-width: 800px) 100vw, 50vw"/></a><figcaption>{panel.caption} <span>Open full resolution ↗</span></figcaption></figure>)}</div></div></section>)}
  <section className="sf-evidence sf-section"><div className="shell"><p className="sf-index">05 / What the work establishes</p><h2>Three levels of evidence</h2><div className="sf-evidence-grid"><article><span>Established</span><h3>Physiology</h3><p>Temperature affects neuronal excitability, and electrocorticography can detect cortical electrical activity.</p></article><article><span>Preclinical</span><h3>Focal cooling</h3><p>Published animal research supports localized, reversible cortical cooling as a seizure-control strategy.</p></article><article><span>Proposed</span><h3>SeizeFreeze</h3><p>The implant architecture, controller, packaging stack, and operating envelope remain design hypotheses requiring validation.</p></article></div></div></section>
  <section className="sf-outcomes sf-section"><div className="shell sf-outcomes-grid"><div><p className="sf-index">06 / Project record</p><h2>From thesis to testable system.</h2></div><div><dl><div><dt>2023 Randall Family Big Idea Competition</dt><dd>Third place · $5,000</dd></div><div><dt>Kuzneski Innovation Cup</dt><dd>Winner · $7,500</dd></div><div><dt>Current work</dt><dd>Thermal modeling, engineering requirements, prototype planning, and translation risk analysis</dd></div></dl><div className="sf-next"><h3>What remains unresolved</h3><p>The safe temperature range, cooling rate, duty cycle, spatial spread, heat rejection, chronic interface response, detection performance, and failure behavior require controlled experimental study.</p></div></div></div></section>
  <nav className="sf-footer-nav" aria-label="Case study navigation"><div className="shell"><Link href="/work">← All work</Link><Link href="/contact">Discuss the work ↗</Link></div></nav>
</article>}
