import Image from "next/image";
import Link from "next/link";

const chapters = [
  { number:"Figures 1–2", eyebrow:"System architecture", title:"Proposed sensing and cooling architecture", body:"The proposed architecture links electrocorticography, temperature sensing, control logic, and localized thermoelectric cooling. The diagrams describe intended behavior; they do not show a tested closed-loop device.", panels:[
    {src:"/images/neurotechnology/seizefreeze/biological-effects.webp",alt:"Concept diagram showing a proposed SeizeFreeze implant above the cortex with sensing, thermoelectric, and cooling layers",caption:"1. Proposed implant architecture and superficial cortical interface."},
    {src:"/images/neurotechnology/seizefreeze/safety-design.webp",alt:"Block diagram of the proposed SeizeFreeze closed-loop sensing and cortical cooling control system",caption:"2. Conceptual event-triggered sensing and control loop."},
  ]},
  { number:"Figures 3–4", eyebrow:"Thermal model", title:"Heat transfer and thermal modeling", body:"A Peltier element can create a temperature gradient when current flows. Device feasibility depends on heat rejection, perfusion, tissue conduction, contact geometry, and control limits. Simulation and bench testing must resolve those variables.", panels:[
    {src:"/images/neurotechnology/seizefreeze/closed-loop-control.webp",alt:"Diagram of thermoelectric cooling physics with hot and cold sides of a Peltier element and the heat-removal equation",caption:"3. Simplified thermoelectric energy balance for the proposed interface."},
    {src:"/images/neurotechnology/seizefreeze/implant-architecture.webp",alt:"Conceptual cortical temperature field and bioheat-transfer equation beneath a localized cooling surface",caption:"4. Conceptual temperature field used to define candidate parameters and boundary conditions."},
  ]},
  { number:"Figures 5–6", eyebrow:"Mechanism and safeguards", title:"Temperature limits and shutdown requirements", body:"Cooling can alter neuronal excitability through several interacting mechanisms. A useful device would need independent temperature limits, rapid shutdown, electrophysiologic confirmation, and protection against thermal overshoot or heat accumulation.", panels:[
    {src:"/images/neurotechnology/seizefreeze/translational-positioning.webp",alt:"Diagram of proposed biological effects of cortical cooling on synaptic transmission, ion channels, neurotransmitter release, and network activity",caption:"5. Proposed cooling effects; this diagram is not a SeizeFreeze experiment."},
    {src:"/images/neurotechnology/seizefreeze/cortical-heat-transfer.webp",alt:"Conceptual safety constraints and failure modes for a focal cortical cooling system",caption:"6. Draft safety framework for bench and preclinical testing."},
  ]},
  { number:"Figures 7–8", eyebrow:"Packaging", title:"Candidate materials and implant packaging", body:"Packaging must address hermeticity, corrosion, biocompatibility, electrical isolation, thermal efficiency, fixation, and surgical access. This stack is the starting point for design controls, materials selection, and packaging experiments.", panels:[
    {src:"/images/neurotechnology/seizefreeze/thermoelectric-cooling.webp",alt:"Exploded conceptual stack showing proposed housing, electronics, thermal spreader, thermoelectric module, insulation, cold plate, interface, and sensors",caption:"7. Candidate packaging stack and material-selection criteria."},
    {src:"/images/neurotechnology/seizefreeze/materials-packaging.webp",alt:"Evidence map separating established physiology, preclinical focal-cooling evidence, and the proposed SeizeFreeze implant architecture",caption:"8. Evidence map: established physiology, preclinical cooling evidence, and the current device concept."},
  ]},
];

export function SeizeFreezeCaseStudy(){return <article className="sf-case">
  <header className="sf-hero"><Image src="/images/neurotechnology/seizefreeze-homepage-hero-v2.webp" alt="Concept visualization of the proposed SeizeFreeze implant, thermoelectric assembly, and localized cortical cooling" fill priority sizes="100vw"/><div className="sf-hero-shade"/><div className="shell sf-hero-content"><p className="sf-kicker">01 / Neurotechnology · Investigational concept</p><h1>Seize<span>Freeze</span></h1><p className="sf-deck">A proposed closed-loop cortical-cooling device for drug-resistant focal epilepsy.</p><dl className="sf-facts"><div><dt>Role</dt><dd>Founder + device lead</dd></div><div><dt>State</dt><dd>Concept + prototype planning</dd></div><div><dt>Recognition</dt><dd>$12.5K documented awards</dd></div><div><dt>Period</dt><dd>2022–present</dd></div></dl></div></header>
  <div className="sf-boundary"><div className="shell"><strong>Development stage</strong><p>Concept and prototype planning. SeizeFreeze has no demonstrated seizure suppression in patients, clinical validation, human testing, or regulatory clearance.</p></div></div>
  <section className="sf-opening sf-section"><div className="shell sf-opening-grid"><p className="sf-index">00 / Problem and role</p><div><h2>A focal-cooling approach to seizure control</h2><p className="sf-lede">The concept pairs seizure sensing with controlled cooling at a focal cortical target. The aim is to suppress pathological activity without removing tissue. I developed the proposed thermoelectric architecture, modeled heat transfer and candidate materials, and explored power, packaging, and safety requirements. Competition awards were received by the Cyberpunk Reality team; the available record does not separate each collaborator’s engineering contribution.</p></div></div></section>
  <section className="sf-film sf-section" aria-labelledby="sf-film-title"><div className="shell"><div className="sf-section-head"><div><p className="sf-index">Concept film / 02:17</p><h2 id="sf-film-title">Early concept film</h2></div><p>An early pitch film describing the proposed device and its intended application.</p></div><video className="sf-video" controls playsInline preload="metadata" poster="/images/neurotechnology/seizefreeze/concept-film-poster.webp" aria-describedby="sf-film-context"><source src="/video/seizefreeze-concept-film.mp4" type="video/mp4"/>Your browser does not support embedded video.</video><p id="sf-film-context" className="sf-film-note">Film context: drug-resistant focal epilepsy, the proposed closed-loop cooling concept, early device imagery, and the intended application. Audio is optional; the case study below contains the substantive engineering narrative.</p></div></section>
  {chapters.map(chapter=><section className="sf-chapter sf-section" key={chapter.number}><div className="shell"><div className="sf-chapter-intro"><p className="sf-index">{chapter.number} / {chapter.eyebrow}</p><div><h2>{chapter.title}</h2><p>{chapter.body}</p></div></div><div className="sf-panel-grid">{chapter.panels.map(panel=><figure className="sf-panel" key={panel.src}><a href={panel.src} target="_blank" rel="noreferrer" aria-label={`Open full-resolution figure: ${panel.caption}`}><Image src={panel.src} alt={panel.alt} width={1448} height={1086} sizes="(max-width: 800px) 100vw, 50vw"/></a><figcaption>{panel.caption} <span>Open full resolution ↗</span></figcaption></figure>)}</div></div></section>)}
  <section className="sf-evidence sf-section"><div className="shell"><p className="sf-index">05 / What the work establishes</p><h2>Evidence and limitations</h2><div className="sf-evidence-grid"><article><span>Design rationale</span><h3>Cooling and sensing</h3><p>The concept uses temperature control and electrocorticography as its proposed cooling and sensing methods.</p></article><article><span>Preclinical</span><h3>Animal cooling experiment</h3><p>Yang and colleagues studied focal cooling in anesthetized rats with experimentally induced neocortical seizures. This supports the cooling rationale, not SeizeFreeze’s effectiveness.</p><a href="https://pubmed.ncbi.nlm.nih.gov/11906508/" target="_blank" rel="noreferrer">Yang et al., Epilepsia (2002) ↗</a></article><article><span>Proposed</span><h3>SeizeFreeze</h3><p>The implant architecture, controller, packaging stack, and operating envelope are the current design under development.</p></article></div></div></section>
  <section className="sf-outcomes sf-section"><div className="shell sf-outcomes-grid"><div><p className="sf-index">06 / Project record</p><h2>Project outputs and competition awards</h2></div><div><dl><div><dt>2023 Randall Family Big Idea Competition</dt><dd>Third place · $5,000</dd></div><div><dt>Kuzneski Innovation Cup</dt><dd>Winner · $7,500</dd></div><div><dt>Current work</dt><dd>Thermal models, engineering requirements, and prototype planning</dd></div></dl><p><a className="text-link" href="https://www.bigidea.pitt.edu/wp-content/uploads/2023/04/Meet-the-Randall-2023-Winners-PDF.pdf" target="_blank" rel="noreferrer">Pitt’s 2023 Randall winner record ↗</a></p><p><a className="text-link" href="https://www.research.pitt.edu/sites/default/files/pitt-research-annual-report-2022-23.pdf" target="_blank" rel="noreferrer">Pitt’s 2022–23 report lists both competitions ↗</a></p><a className="sf-pitch-link" href="https://www.youtube.com/watch?v=Dmcy0BdBy6g&t=189s" target="_blank" rel="noreferrer"><strong>Watch the original founder pitch</strong><span>Starts at 3:09 ↗</span></a><div className="sf-panel-grid"><figure className="sf-panel"><Image src="/images/neurotechnology/seizefreeze/founder-early-pitch.webp" alt="Arjan Singh Puniani presenting an early-stage SeizeFreeze pitch" width={1200} height={1200} sizes="(max-width: 800px) 100vw, 50vw"/><figcaption>Early-stage founder pitch during the project’s competition phase.</figcaption></figure><figure className="sf-panel"><Image src="/images/neurotechnology/seizefreeze/kuzneski-innovation-cup.webp" alt="Cyberpunk Reality team holding the Kuzneski Innovation Cup trophy with a graphic noting the seven-thousand-five-hundred-dollar award" width={1200} height={1200} sizes="(max-width: 800px) 100vw, 50vw"/><figcaption>Kuzneski Innovation Cup · $7,500 documented award.</figcaption></figure></div><div className="sf-next"><h3>Next experiments and unresolved requirements</h3><p>Bench experiments would need to measure cooling rate, spatial heat spread, heat rejection, and shutdown behavior. Safe temperature limits, duty cycle, detection performance, and chronic tissue response remain unresolved. The design diagrams and competition awards do not establish safety or effectiveness.</p></div></div></div></section>
  <nav className="sf-footer-nav" aria-label="Case study navigation"><div className="shell"><Link href="/work">← All work</Link><Link href="/contact">Discuss the work ↗</Link></div></nav>
</article>}
