import{chromium,expect}from'@playwright/test';import{writeFile}from'node:fs/promises';
const base=process.env.SHOULDER_URL||'http://127.0.0.1:4190/holoanatomy/shoulder/';const out='Documentation/shoulder-qa';
const browser=await chromium.launch({channel:'chrome',headless:true});const failures=[],errors=[],results={};
async function load(page,url=base){page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().includes('favicon'))failures.push(r.url());});await page.goto(url);await page.waitForFunction(()=>window.shoulderStudio?.ready,{timeout:30000});await page.waitForTimeout(600);}
async function capture(page,name){await page.waitForTimeout(600);await page.screenshot({path:`${out}/${name}.png`});}
async function pointFor(page,id){return page.evaluate(id=>{const {scene}=shoulderStudio;const c=scene.project(id),rect=scene.canvas.getBoundingClientRect();for(let ring=0;ring<150;ring+=10)for(let a=0;a<Math.PI*2;a+=.35){const x=rect.left+c.x+Math.cos(a)*ring,y=rect.top+c.y+Math.sin(a)*ring;if(x<rect.left||y<rect.top||x>rect.right||y>rect.bottom)continue;if(scene.pick(x,y)===id)return{x,y};}return null;},id);}
try{
 const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});await load(page);await capture(page,'initial');
 for(const view of ['posterior','anterior','superior','lateral','joint','vascular']){await page.selectOption('#view-select',view);await capture(page,view);}
 await page.selectOption('#view-select','posterior');await page.waitForTimeout(700);
 const p=await pointFor(page,'FJ1500');if(!p)throw Error('Infraspinatus cannot be picked in posterior view');await page.mouse.click(p.x,p.y);await expect(page.locator('#context h2')).toHaveText('Infraspinatus');await capture(page,'selected');
 await page.click('[data-action=isolate]');expect(await page.evaluate(()=>shoulderStudio.scene.materials(shoulderStudio.scene.meshes.get('FJ3384'))[0].opacity)).toBeLessThan(1);await page.click('#reset');await page.waitForTimeout(650);
 const yaw=await page.evaluate(()=>shoulderStudio.scene.yaw);await page.mouse.move(600,500);await page.mouse.down();await page.mouse.move(710,540,{steps:12});await page.mouse.up();expect(await page.evaluate(()=>shoulderStudio.state.selected)).toBe(null);expect(await page.evaluate(()=>shoulderStudio.scene.yaw)).not.toBe(yaw);
 const oldTarget=await page.evaluate(()=>shoulderStudio.scene.target.toArray());await page.locator('#specimen').dispatchEvent('wheel',{deltaX:30,deltaY:20,deltaMode:0});expect(await page.evaluate(()=>shoulderStudio.scene.target.toArray())).not.toEqual(oldTarget);
 const d=await page.evaluate(()=>shoulderStudio.scene.distance);await page.locator('#specimen').dispatchEvent('wheel',{deltaY:-12,ctrlKey:true,deltaMode:0,clientX:600,clientY:400});expect(await page.evaluate(()=>shoulderStudio.scene.distance)).toBeLessThan(d);
 await page.click('#reset');await page.click('[data-mode=peel]');await page.locator('#peel-range').fill('2');await page.click('[data-action=separate]');expect(await page.evaluate(()=>shoulderStudio.state.staged.length)).toBe(1);await capture(page,'peel');await page.click('[data-action=undo]');expect(await page.evaluate(()=>shoulderStudio.state.staged.length)).toBe(0);
 await page.click('[data-mode=learn]');for(let i=0;i<4;i++)await page.click('[data-action=next]');await capture(page,'learn');
 await page.click('[data-mode=quiz]');await page.waitForTimeout(650);await capture(page,'quiz');
 const target=await page.evaluate(()=>['FJ1506','FJ1504','FJ1500','FJ1508'][shoulderStudio.state.quiz.index%4]);const hit=await pointFor(page,target);if(!hit)throw Error('Quiz target is not pickable');await page.mouse.click(hit.x,hit.y);await expect(page.locator('#feedback')).toContainText('Correct');expect(await page.evaluate(()=>shoulderStudio.state.quiz.score)).toBe(1);await page.click('[data-action=quiz-next]');expect(await page.evaluate(()=>shoulderStudio.state.quiz.index)).toBe(1);
 await page.click('[data-mode=explore]');await page.waitForTimeout(650);await capture(page,'atlas');
 await page.evaluate(()=>{shoulderStudio.scene.frameTimes=[];shoulderStudio.scene.profileUntil=performance.now()+2200;shoulderStudio.scene.invalidate();});
 await page.mouse.move(450,400);await page.mouse.down();await page.mouse.move(700,500,{steps:90});await page.mouse.up();await page.waitForTimeout(2300);results.desktop=await page.evaluate(()=>({metrics:shoulderStudio.metrics(),resources:performance.getEntriesByType('resource').filter(x=>x.name.includes('/shoulder/')).map(x=>({url:x.name,bytes:x.transferSize,duration:x.duration})),interactive:performance.getEntriesByName('shoulder-interactive')[0]?.startTime}));
 // Real touch events via Chromium's emulated mobile input; not physical-iPhone performance.
 const ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mobile=await ctx.newPage();await load(mobile);await capture(mobile,'mobile-initial');expect(await mobile.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 const cdp=await ctx.newCDPSession(mobile);const touch=async(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y,id])=>({x,y,id,radiusX:4,radiusY:4}))});
 const md=await mobile.evaluate(()=>shoulderStudio.scene.distance);await touch('touchStart',[[150,320,1],[240,320,2]]);await touch('touchMove',[[125,325,1],[270,325,2]]);await touch('touchEnd',[]);expect(await mobile.evaluate(()=>shoulderStudio.scene.distance)).toBeLessThan(md);expect(await mobile.evaluate(()=>shoulderStudio.state.selected)).toBe(null);
 await mobile.click('#reset');await mobile.waitForTimeout(700);await touch('touchStart',[[190,320,1]]);await touch('touchMove',[[225,335,1]]);await touch('touchEnd',[]);expect(await mobile.evaluate(()=>shoulderStudio.state.selected)).toBe(null);
 for(const mode of ['peel','learn','quiz']){await mobile.click(`[data-mode=${mode}]`);if(mode==='peel'){await mobile.locator('#peel-range').fill('2');await mobile.click('[data-action=separate]');}await capture(mobile,`mobile-${mode}`);}
 await mobile.click('[data-mode=explore]');await mobile.evaluate(()=>scrollTo(0,0));await mobile.setViewportSize({width:844,height:390});await mobile.click('#reset');await capture(mobile,'mobile-landscape');expect(await mobile.evaluate(()=>document.documentElement.scrollWidth)).toBe(844);
 results.mobile=await mobile.evaluate(()=>shoulderStudio.metrics());await ctx.close();
 const fallback=await browser.newPage({viewport:{width:1000,height:800}});await load(fallback,base+'?format=obj');expect(await fallback.evaluate(()=>shoulderStudio.scene.transport)).toBe('obj');expect(await fallback.evaluate(()=>shoulderStudio.scene.meshes.size)).toBe(20);results.obj=await fallback.evaluate(()=>shoulderStudio.metrics());await fallback.close();
 const lod=await browser.newPage();await load(lod,base+'?lod=2');expect(await lod.evaluate(()=>shoulderStudio.scene.meshes.size)).toBe(20);results.lod2=await lod.evaluate(()=>shoulderStudio.metrics());await lod.close();
 expect(errors).toEqual([]);expect(failures).toEqual([]);results.status='PASS';console.log('PASS browser: cameras, mesh picking, orbit suppression, pan, pinch, isolate, peel/undo, lesson, actual 3D quiz, mobile touch/layout, OBJ fallback and LOD2.');
} catch(e){results.status='FAIL';results.error=e.stack;throw e;}finally{await writeFile(out+'/browser-results.json',JSON.stringify({...results,errors,failures},null,2));await browser.close();}
