import type { Metadata } from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Belmont Motorsport Systems",description:"Arjan Singh Puniani's academic analysis of risk, mitigation, emergency operations, and medical coordination under race-day constraints.",alternates:{canonical:"/work/belmont-motorsport-systems"}};
const modules=[
  ["Risk register","Ranked 16 event risks using consistent likelihood and impact criteria.","Academic risk-analysis assignment"],
  ["Mitigation controls","Mapped heat, medical surge, crash, fire, hazardous-material, weather, security, and system-failure controls.","Academic mitigation assignment"],
  ["Decision ownership","Separated Race Control, fire-rescue, medical, security, operations, and public-information responsibilities.","Proposed emergency-operations annex"],
  ["Recovery gates","Defined conditions for track status, containment, communications, medical coverage, access, security, and records.","Proposed emergency-operations annex"],
] as const;
export default function BelmontSystems(){return <><header className="page-hero"><div className="shell"><p className="eyebrow">Motorsport systems · Academic work · 2026</p><h1>Planning under race-day constraints.</h1><p>An academic study of how risk information becomes decision ownership, mitigation controls, and conditions for resuming operations.</p></div></header><section className="section"><div className="shell case-intro"><p className="eyebrow">Scope</p><div><h2>A risk matrix matters only when someone knows what to do with it.</h2><p>This Belmont Abbey College coursework examined a major road-racing weekend as a constrained operating environment. It connected event hazards with triggers, assigned roles, communications, and recovery conditions.</p><div className="notice"><strong>Boundary:</strong> This was an academic, role-based proposal. It was not commissioned, reviewed, or approved by Sonoma Raceway, NASCAR, or a public agency.</div></div></div></section><section className="section"><div className="shell"><p className="eyebrow">Operational model</p><h2>From incident to accountable record</h2><div className="motorsport-flow" role="img" aria-label="Incident leads to scene observations, an immediate safety decision, medical handoff, and follow-up documentation">{["Incident","Scene observations","Immediate safety decision","Medical handoff","Follow-up record"].map((item,index)=><div key={item}><span>0{index+1}</span><strong>{item}</strong>{index<4&&<i>→</i>}</div>)}</div></div></section><section className="section"><div className="shell"><p className="eyebrow">Modules</p><div className="motorsport-modules">{modules.map(([title,decision,evidence])=><article key={title}><h2>{title}</h2><p>{decision}</p><dl><dt>My contribution</dt><dd>Analysis, synthesis, and plan authorship</dd><dt>Evidence</dt><dd>{evidence}</dd><dt>Limitation</dt><dd>Requires reconciliation with current venue, sanctioning-body, emergency medical services, and hospital procedures before any operational use.</dd></dl></article>)}</div></div></section><section className="section clinical-boundary"><div className="shell case-intro"><p className="eyebrow">Related work</p><div><h2>Mechanism-to-Medical Center</h2><p>The separate neurotrauma project focuses on crash mechanism, occupant protection, neurological findings, disposition, and handoff documentation.</p><Link className="text-link" href="/work/motorsport-neurotrauma-toolkit">Open the neurotrauma toolkit →</Link></div></div></section></>}
