import type { Metadata } from "next";
import Link from "next/link";
import { ProcessFlow } from "@/components/SystemVisuals";

export const metadata: Metadata = {
  title: "Mechanism-to-Medical Center — Exploratory Motorsport Neurotrauma Toolkit",
  description: "An exploratory documentation and escalation framework connecting crash mechanics with acute neurologic assessment in local and regional motorsport.",
  alternates: { canonical: "/work/motorsport-neurotrauma-toolkit" },
  openGraph: { title: "Mechanism-to-Medical Center", description: "An exploratory, non-validated motorsport neurotrauma documentation framework.", url: "/work/motorsport-neurotrauma-toolkit" },
};

export default function NeurotraumaToolkitPage() {
  return <article className="case-study toolkit-case">
    <header className="case-study-hero"><div className="shell"><div className="case-breadcrumb"><Link href="/motorsport">Motorsport</Link><span>/</span><span>Crash & neurotrauma</span></div><div className="case-title-grid"><div><p className="overline"><span /> Motorsport medicine / documentation</p><h1>Mechanism-to-Medical Center.</h1><p className="case-deck">An exploratory documentation and escalation framework for connecting crash mechanics with acute neurologic assessment.</p></div><aside><span className="status">EXPLORATORY</span><dl><dt>Context</dt><dd>Grassroots / regional motorsport</dd><dt>Role</dt><dd>Systems analysis + technical writing</dd><dt>Artifact</dt><dd>Version 0.2 pilot draft</dd><dt>Review</dt><dd>External critique documented</dd><dt>Validation</dt><dd>None claimed</dd></dl></aside></div></div></header>

    <section className="case-disclaimer"><div className="shell"><strong>Clinical boundary</strong><p>This is a pilot documentation concept—not a validated diagnostic instrument, clinical standard, sanctioning-body procedure, or substitute for licensed clinical judgment. The page explains the information architecture; it does not reproduce the full medical-warning and disposition algorithm for independent use.</p></div></section>

    <div className="shell case-body">
      <section className="case-section"><div className="case-section-label"><span>01</span><p>Problem</p></div><div className="case-section-content"><h2>A handoff can preserve symptoms and still lose the crash.</h2><p className="lead">Mechanism, occupant-protection context, neurologic observations, and initial disposition can be recorded in separate places—or not connected at all. The concept asks how one concise record might preserve those relationships without pretending to replace clinical authority.</p></div></section>

      <section className="case-section case-section-wide"><div className="case-section-label"><span>02</span><p>Core model</p></div><div className="case-section-content"><h2>Connect four evidence groups.</h2><ProcessFlow label="Exploratory mechanism-to-disposition workflow" steps={[{label:"Crash mechanism",note:"direction, energy, sequence"},{label:"Occupant protection",note:"restraints, helmet, vehicle context"},{label:"Neurologic observations",note:"acute signs and reported change"},{label:"Escalation",note:"raise concern through appropriate authority"},{label:"Initial disposition",note:"record the resulting decision"}]} /><p className="source-line">The framework preserves information relationships. It does not calculate injury probability or recommend treatment.</p></div></section>

      <section className="case-section"><div className="case-section-label"><span>03</span><p>Information design</p></div><div className="case-section-content"><h2>Separate observation from interpretation.</h2><div className="evidence-layers"><article><span>Observed</span><strong>What happened or was seen</strong><p>Mechanism, protection context, signs, and changes—recorded without adding a diagnosis.</p></article><article><span>Interpreted</span><strong>Why concern changed</strong><p>A concise explanation of the relationship between mechanism and observations.</p></article><article><span>Decided</span><strong>What authorized personnel did</strong><p>Escalation, disposition, and handoff recorded as actions, not implied outcomes.</p></article></div></div></section>

      <section className="case-section"><div className="case-section-label"><span>04</span><p>Review posture</p></div><div className="case-section-content"><h2>Feedback sought is not endorsement.</h2><p>March 2026 correspondence documents ICMS-facilitated review requests and substantive critique from two physicians working in motorsport medicine. The responses tested the concept rather than approving it.</p><div className="evidence-layers"><article><span>Terminology</span><strong>Avoid race-control ambiguity</strong><p>Reviewers flagged that “red flag” has a specific racing meaning and should not be reused for medical warning signs.</p></article><article><span>Workflow</span><strong>Separate scene work from later review</strong><p>Feedback questioned which vehicle and protection fields belong at the scene, in the medical record, or in an after-action dataset.</p></article><article><span>Authority</span><strong>Reconcile local and series rules</strong><p>Reviewers emphasized race-control direction, user training, and series-specific return-to-participation requirements.</p></article></div><p className="source-line">The correspondence establishes review and critique—not ICMS, reviewer, venue, or sanctioning-body endorsement.</p></div></section>

      <section className="case-section limitations-section"><div className="case-section-label"><span>05</span><p>Limitations</p></div><div className="case-section-content"><h2>Deliberately narrow claims.</h2><ul><li>No validation study, sensitivity, specificity, reliability, or outcome data.</li><li>No clinical-decision-support claim.</li><li>No sanctioning-body standard, venue adoption, deployment, or implementation result.</li><li>No endorsement implied by correspondence, ICMS facilitation, or reviewer participation.</li><li>No replacement for local rules, credentialed assessment, emergency procedures, or lawful medical authority.</li><li>External critique identified unresolved questions about users, terminology, observational reliability, workflow burden, and series-specific rules.</li></ul><p className="source-line">Primary sources reviewed: <em>Mechanism-to-Medical Center</em> Version 0.2 pilot draft; <em>High Alert and Disposition Algorithm</em> Version 0.2 pilot draft; and March 25–26, 2026 review correspondence.</p></div></section>

      <footer className="case-next"><p>See the operating-system scale</p><Link href="/work/sonoma-emergency-operations"><strong>Emergency operations at Sonoma</strong><span>↗</span></Link></footer>
    </div>
  </article>;
}
