import {chromium,browserOptions} from './runtime.mjs';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';
const root=path.resolve(process.argv[2]||'.'),out=process.argv[3]||'qa/poses',states=(process.argv[4]||'idle,walk,sit,drink,talk,watch,swingForehand,swingBackhand,serve').split(',');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]||'/')),f=p===root?path.join(root,'index.html'):p;if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');fs.createReadStream(f).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch(browserOptions);const page=await browser.newPage({viewport:{width:1100,height:760}});let seed=17;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32};const results=[];
try{await page.goto(`http://127.0.0.1:${server.address().port}/?debug=1`);await page.waitForFunction(()=>window.__rh?.ready);await page.evaluate(()=>{const g=window.__rh.game;g.clock.paused=true;g.ui.closeContext();g.audio.enabled=false;for(const a of [...g.activities.active])g.cancelActivity(a);g.camera.focus(-5,2,16);g.camera.desiredAzimuth=.15;g.camera.desiredElevation=.35;for(const c of [...g.characters,g.player])c.position.set(20,0,20);});await page.waitForTimeout(2000);
for(const state of states){const times=Array.from({length:20},()=>random()*1.6).sort((a,b)=>a-b);let prev=0;await page.evaluate(state=>{const g=window.__rh.game,c=g.actor('mika');c.position.set(-5,0,2);c.path=[];c.yaw=0;c.face({x:-5,y:0,z:5});c.seatDepth=state==='sit'?.8:0;c.setAnimation('idle');c.update(1);c.trigger(state);if(state==='walk'||state==='jog')c.goTo({x:-5,y:0,z:5});},state);
for(let i=0;i<20;i++){const dt=times[i]-prev;prev=times[i];const data=await page.evaluate(dt=>{const c=window.__rh.game.actor('mika');for(let t=0;t<dt;t+=1/60)c.update(Math.min(1/60,dt-t));return c.debugKinematics()},dt);results.push({state,frame:i,time:times[i],kinematics:data});await page.waitForTimeout(35);await page.screenshot({path:`${out}/${state}-${String(i).padStart(2,'0')}.png`,clip:{x:380,y:150,width:340,height:430},timeout:60000});}console.log('POSE',state);}
fs.writeFileSync(`${out}/frames.json`,JSON.stringify(results,null,2));}finally{await browser.close();await new Promise(r=>server.close(r));}
