import {chromium,browserOptions} from './runtime.mjs';
import {homedir} from 'node:os';import {pathToFileURL} from 'node:url';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';
const api=await import(pathToFileURL(path.join(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')));
const root=path.resolve(process.argv[2]||'.'),label=process.argv[3]||'matrix',results=[];
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]||'/')),f=p===root?path.join(root,'index.html'):p;if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');fs.createReadStream(f).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
for(const name of ['chromium','webkit','firefox']){let browser;const r={browser:name,errors:[]};try{browser=await api[name].launch(name==='chromium'?browserOptions:name==='webkit'?{headless:true,executablePath:path.join(homedir(),'Library/Caches/ms-playwright/webkit-2359/pw_run.sh')}:{headless:true});const page=await browser.newPage({viewport:{width:1100,height:760}});page.on('pageerror',e=>r.errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/?debug=1`);await page.waitForFunction(()=>window.__rh?.ready,null,{timeout:60000});r.startup=true;
 await page.evaluate(()=>{const g=window.__rh.game;g.clock.paused=true;g.autosave=-1e6;g.ui.closeContext()});await page.click('#bookBtn');await page.click('[data-tab="people"]');r.people=await page.locator('#bookContent').innerText();await page.keyboard.press('Escape');await page.click('#saveBtn');await page.waitForTimeout(500);await page.reload();await page.waitForFunction(()=>window.__rh?.ready);r.reload=true;
 r.saveConflict=await page.evaluate(async()=>{const {SaveSystem}=await import('./dist/persistence/SaveSystem.js');const key='qa-conflict-'+Date.now(),a=new SaveSystem(key),b=new SaveSystem(key);await a.load();await b.load();await a.save({coins:111});let detected=false,message='';try{await b.save({coins:222})}catch(e){detected=true;message=e.message}const c=new SaveSystem(key),saved=await c.load();return {detected,message,coins:saved.state.coins}});
 await page.evaluate(()=>window.__rh.game.ui.closeContext());await page.locator('#game').focus();await page.keyboard.press('2');r.keyboard=await page.locator('#contextTitle').innerText();await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});await page.click('#bookBtn');await page.waitForFunction(()=>Number(getComputedStyle(document.querySelector('#book')).opacity)===1);r.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.screenshot({path:`qa/${label}-${name}.png`,timeout:60000});r.status='tested';
 }catch(e){r.status=r.startup?'failed':'unavailable';r.reason=e.message;}finally{if(browser)await browser.close();results.push(r);fs.writeFileSync(`qa/${label}.json`,JSON.stringify(results,null,2));console.log(name,r.status,r.saveConflict??r.reason);}}
await new Promise(r=>server.close(r));
